name: week5-ci

on:
  push:
    branches:
      - 'master'
      - 'week5'

env:
  DOCKER_IMAGE_NAME: sd-concept
  PROJECT_NAME: sd-concept-project
  UI_SERVICE_NAME: streamlit-ui-service


jobs:
  streamlit-ui-deploy:
    runs-on: ubuntu-latest
    name: build docker image and deploy to cloud run

    steps:
    - uses: actions/checkout@v2
    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: gcr.io
        project_id: ${{ env.PROJECT_NAME }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}
        image_tag: latest
        dockerfile: ./week5/Dockerfile
        context: ./week5

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.UI_SERVICE_NAME }} --image=gcr.io/${{ env.PROJECT_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest --max-instances=10 --min-instances=1 --port=1234 --region=us-east1 --cpu=4 --memory=8Gi --allow-unauthenticated

