name: week5-ci

on:
  push:
    branches:
      - 'master'
      - 'week5'

jobs:

  streamlit-ui-deploy:
    runs-on: ubuntu-latest
    name: build docker image and deploy to cloud run

    steps:
#    - uses: actions/checkout@v2
#    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
#      with:
#        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
#        registry: gcr.io
#        project_id: sd-concept-project
#        image_name: sd-concept
#        image_tag: latest
#        dockerfile: ./week5/Dockerfile
#        context: ./week5

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Deploy to Cloud Run
      run: gcloud run deploy sd-concept-project --image=gcr.io/sd-concept-project/sd-concept:latest --max-instances=10 --min-instances=1 --port=1234 --region=us-east1 --cpu=4 --memory=8Gi

